[package]
name = "Graphene"
version = "0.1.0"
authors = ["Toure Dunnon <tdunnon@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.0"
zip = "0.5"
glob = "0.3.0"
walkdir = "2.2.9"
flate2 = "1.0.11"
tar = "0.4.26"
rusqlite = "0.20.0"