[package]
name = "graphene"
version = "0.1.0"
authors = ["Toure <tdunnon@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
rocket_codegen = "0.4.2"
diesel = { version = "1.4.2", features = ["postgres"] }
dotenv = "0.14.1"